version: '3.3'
services:
  db:
    image: mysql
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
    - '3306:3306'
    volumes:
    - 'api_data:/var/lib/mysql'

  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    volumes:
    - "./resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
    - '9090:9090'
   
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    ports: 
    - '3000:3000'
    
    
volumes:
  api_data: