server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/api"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG