server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    name: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG